version = 0.1

[default.deploy.parameters]
stack_name = "ws-serverless-patterns-polling"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-polling"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "OrdersTablename=\"ws-serverless-patterns-orders-OrdersTable-2V7V5NGX5I4R\" UserPool=\"us-west-1_vOrI5g3Yb\" Stage=\"dev\""
image_repositories = []

[default.global.parameters]
region = "us-west-1"
